In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, mean_absolute_error

In [29]:
df=pd.read_csv("50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [30]:
df2=pd.read_csv("Social_Network_Ads.csv")
df2.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

## steps for building baseline classification model

## Data Cleaning
 initial steps are alwas data preprocessing (cleaning , sorting etc)

## Step One
split the data into features/independent/input and targets/dependent/output

In [31]:
X= df2.copy().drop(columns=["User ID"]) # independent
y=X.pop("Purchased") # dependent

In [32]:
X

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [33]:
y.value_counts()

0    257
1    143
Name: Purchased, dtype: int64

# step two (if required)
encoding categories columns

In [34]:
X_dummy=pd.get_dummies(X, columns=["Gender"], drop_first=True )
X_dummy

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

## Step three
petition the data into train and text

In [35]:
x_train, x_test, y_train, y_test= train_test_split(X_dummy, y, test_size=0.1, random_state=42)

In [36]:
x_train

Age  EstimatedSalary  Gender_Male
381   48            33000            1
55    24            55000            0
76    18            52000            1
25    47            20000            1
82    20            49000            1
..   ...              ...          ...
71    24            27000            0
106   26            35000            0
270   43           133000            0
348   39            77000            1
102   32            86000            0

[360 rows x 3 columns]

## step four
build the model

In [37]:
dt=DecisionTreeClassifier(random_state=42) # creating the instance of the DecisionTreeClassifier algorithm
model_1= dt.fit(x_train, y_train ) # training the model

In [38]:
#second algorithm
svm= SVC(random_state=42)
model_2=svm.fit(x_train, y_train)

In [46]:
#third algorithm
lr= LogisticRegression(random_state=42)
model_3= lr.fit(x_train, y_train)

## step five
model evaluation

In [47]:
prediction_1= model_1.predict(x_test)
eval_1=accuracy_score(y_test, prediction_1)
eval_1_c= confusion_matrix(y_test, prediction_1)

print(f"the accuracy score by {dt} is {eval_1} \n")
print(f"the confusion matrix for {dt} is \n{eval_1_c} \n")

the accuracy score by DecisionTreeClassifier(random_state=42) is 0.825 

the confusion matrix for DecisionTreeClassifier(random_state=42) is 
[[23  4]
 [ 3 10]] 



In [48]:
prediction_2= model_2.predict(x_test)
eval_2=accuracy_score(y_test, prediction_2)
eval_2_c= confusion_matrix(y_test, prediction_2)

print(f"the accuracy score by {svm} is {eval_2} \n")
print(f"the confusion matrix for {svm} is \n{eval_2_c}")

the accuracy score by SVC(random_state=42) is 0.75 

the confusion matrix for SVC(random_state=42) is 
[[26  1]
 [ 9  4]]


In [49]:
prediction_3= model_3.predict(x_test)
eval_3=accuracy_score(y_test, prediction_3)
eval_3_c= confusion_matrix(y_test, prediction_3)

print(f"the accuracy score by {lr} is {eval_3} \n")
print(f"the confusion matrix for {lr} is \n{eval_3_c}")

the accuracy score by LogisticRegression(random_state=42) is 0.675 

the confusion matrix for LogisticRegression(random_state=42) is 
[[27  0]
 [13  0]]
